### Add user #1

POST http://localhost:8080/users
Content-Type: application/json
Accept: application/json

{
  "email": "john@yahoo.com",
  "name": "John Carmack",
  "login": "john_c",
  "birthday": "1970-12-31"
}

> {%
    client.test("Response code 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("User id is 1", function() {
        client.assert(response.body.id === 1, "Wrong user id");
    })
%}

<> 2024-09-15T065959.200.json
<> 2024-09-15T065920.200.json
<> 2024-09-15T065639.200.json
<> 2024-09-15T064903.200.json
<> 2024-09-15T064822.200.json
<> 2024-09-15T063928.200.json
<> 2024-09-15T063905.500.json
<> 2024-09-15T062956.200.json
<> 2024-09-07T145247.404.json
<> 2024-09-07T144934.500.json

### Add user #2

POST http://localhost:8080/users
Content-Type: application/json
Accept: application/json

{
  "email": "jack@google.com",
  "name": "Jack Sparrow",
  "login": "jack_s",
  "birthday": "1620-06-30"
}

> {%
    client.test("Response code 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("User id is 2", function() {
        client.assert(response.body.id === 2, "Wrong user id");
    })
%}

### Add film #1

POST http://localhost:8080/films
Content-Type: application/json
Accept: application/json

{
  "name": "Matrix",
  "description": "Legendary movie",
  "releaseDate": "1999-03-24",
  "duration": 136,
  "mpa": {"id" : 4},
  "genres" : [
    {"id" : 6}
  ]
}

> {%
    client.test("Response code 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Film id is 1", function() {
        client.assert(response.body.id === 1, "Wrong film id");
    })
%}

<> 2024-09-15T070000.200.json
<> 2024-09-15T065921.200.json
<> 2024-09-15T065639-1.200.json

### User #1 adds like

PUT http://localhost:8080/films/1/like/1?mark=9

<> 2024-09-15T065921.404.json

### Film #1 has rating 9

GET http://localhost:8080/films/1
Accept: application/json

> {%
    client.test("Response code 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Film rating is 9", function() {
        client.assert(response.body.rating === 9, "Wrong film mark")
    })
%}

### User #2 add like

PUT http://localhost:8080/films/1/like/2?mark=6

### Film #1 has rating 7.5

GET http://localhost:8080/films/1
Accept: application/json

> {%
    client.test("Response code 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Film mark is 9", function() {
        client.assert(response.body.rating === 7.5, "Wrong film mark")
    })
%}
