spring:
  main:
    banner-mode: off
  mvc:
    log-resolved-exception: true
  datasource:
    url: jdbc:h2:mem:filmorate
logging:
  level:
    ru.yandex.practicum.filmorate.controller: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG